### ISSUE TITLE
java.lang.NullPointerException při zpracování katastrálních území

### ISSUE THREAD

**Issue by cikorka** [fordfrog/ruian2pgsql#25]
Ahoj,
díky za skvělý nástroj... !

Bohužel při importu dat, mi to při zpracování katastrálních území vyhazuje NullPointerException. Chyba se stává jen u některých souborů.

Dík

```
$ java -cp ruian2pgsql-1.5.0-jar-with-dependencies.jar –com.fordfrog.ruian2pgsql.App  --db-connection-url >"jdbc:postgresql://localhost/ruian?user=spring&password=spring" --no-gis --truncate-all --create-tables --input-dir "/Users/cikorka/Downloads"
Initializing database schema...
Truncating all data tables...
Processing file /Users/cikorka/Downloads/20140228_ST_UZSZ.xml.gz
Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:VymennyFormatTypy:v1 VerzeVFR
Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:VymennyFormatTypy:v1 PlatnostDatK
  Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:CommonTypy:v1 ISUI
  Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:CommonTypy:v1 ISKN
File processed in 17701 ms
Processing file /Users/cikorka/Downloads/20140331_ST_UZSZ.xml.gz
Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:VymennyFormatTypy:v1 VerzeVFR
Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:VymennyFormatTypy:v1 PlatnostDatK
  Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:CommonTypy:v1 ISUI
  Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:CommonTypy:v1 ISKN
Exception in thread "main" java.lang.NullPointerException
        at com.fordfrog.ruian2pgsql.convertors.KatastralniUzemiConvertor.fill(KatastralniUzemiConvertor.java:121)
        at com.fordfrog.ruian2pgsql.convertors.KatastralniUzemiConvertor.fill(KatastralniUzemiConvertor.java:41)
        at com.fordfrog.ruian2pgsql.convertors.AbstractSaveConvertor.insertItem(AbstractSaveConvertor.java:283)
        at com.fordfrog.ruian2pgsql.convertors.AbstractSaveConvertor.saveData(AbstractSaveConvertor.java:246)
        at com.fordfrog.ruian2pgsql.convertors.AbstractSaveConvertor.convert(AbstractSaveConvertor.java:168)
        at com.fordfrog.ruian2pgsql.convertors.CollectionConvertor.processElement(CollectionConvertor.java:93)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.DataConvertor.processElement(DataConvertor.java:184)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.ExchangeFormatConvertor.processElement(ExchangeFormatConvertor.java:73)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.processElement(MainConvertor.java:308)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.readInputStream(MainConvertor.java:287)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.processFile(MainConvertor.java:244)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.convert(MainConvertor.java:131)
        at com.fordfrog.ruian2pgsql.App.main(App.java:133)
```

```
$ java -cp ruian2pgsql-1.5.0-jar-with-dependencies.jar com.fordfrog.ruian2pgsql.App  --db-connection-url "jdbc:postgresql://localhost/ruian?user=spring&password=spring" --no-gis --truncate-all --create-tables --input-dir "/Users/cikorka/Downloads"                 
Initializing database schema...
Truncating all data tables...
Unsupported file extension, ignoring file /Users/cikorka/Downloads/.DS_Store
Processing file /Users/cikorka/Downloads/20140228_OB_599999_UZSZ.xml.gz
Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:VymennyFormatTypy:v1 VerzeVFR
Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:VymennyFormatTypy:v1 PlatnostDatK
  Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:CommonTypy:v1 ISUI
  Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:CommonTypy:v1 ISKN
Exception in thread "main" java.lang.AbstractMethodError: org.postgresql.jdbc3.Jdbc3Connection.createArrayOf(Ljava/lang/String;[Ljava/lang/Object;)Ljava/sql/Array;
        at com.fordfrog.ruian2pgsql.utils.PreparedStatementEx.setIntArray(PreparedStatementEx.java:158)
        at com.fordfrog.ruian2pgsql.convertors.StavebniObjektConvertor.fill(StavebniObjektConvertor.java:195)
        at com.fordfrog.ruian2pgsql.convertors.StavebniObjektConvertor.fill(StavebniObjektConvertor.java:42)
        at com.fordfrog.ruian2pgsql.convertors.AbstractSaveConvertor.insertItem(AbstractSaveConvertor.java:283)
        at com.fordfrog.ruian2pgsql.convertors.AbstractSaveConvertor.saveData(AbstractSaveConvertor.java:246)
        at com.fordfrog.ruian2pgsql.convertors.AbstractSaveConvertor.convert(AbstractSaveConvertor.java:168)
        at com.fordfrog.ruian2pgsql.convertors.CollectionConvertor.processElement(CollectionConvertor.java:93)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.DataConvertor.processElement(DataConvertor.java:220)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.ExchangeFormatConvertor.processElement(ExchangeFormatConvertor.java:73)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.processElement(MainConvertor.java:308)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.readInputStream(MainConvertor.java:287)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.processFile(MainConvertor.java:244)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.convert(MainConvertor.java:131)
        at com.fordfrog.ruian2pgsql.App.main(App.java:133)
```

**Comment by webbrain-dev** [comment]
Ahoj, díky za detailní report! Otevřel jsem PR #42, který opravuje NullPointerException při zpracování katastrálních území – přidává kontrolu na chybějící/null hodnoty, aby se import nezasekl u některých souborů. Uvidíme, jestli to pomůže i u tvých dat.
