### ISSUE TITLE
Změna struktury

### ISSUE THREAD

**Issue by vumop** [fordfrog/ruian2pgsql#35]
Dobrý den,
chtěl jsem se poradit. Je možné, že se změnila struktura RUIAN? U 385 obcí se mi nedaří je naimportovat do dtb.
java -cp .:./ruian2pgsql/target/ruian2pgsql-1.6.1-jar-with-dependencies.jar:/ruian2pgsql/target/jdbc-driver.jar com.fordfrog.ruian2pgsql.App --db-connection-url  --dest-srid 102067 --ignore-invalid-gml --input-dir /ruian2pgsql/xml
Recreating RÚIAN statistics views...
Processing file /ruian2pgsql/xml/20170131_OB_531545_UKSH.xml.gz
Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:VymennyFormatTypy:v1 VerzeVFR
Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:VymennyFormatTypy:v1 PlatnostDatK
  Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:CommonTypy:v1 ISUI
  Warning: Ignoring unsupported element urn:cz:isvs:ruian:schemas:CommonTypy:v1 ISKN
Invalid GML: <gml:pointMembers xmlns:gml="http://www.opengis.net/gml/3.2"><gml:Point gml:id="DOB.531545.1"><gml:pos>-759963.00 -1055745.00</gml:pos></gml:Point></gml:pointMembers>
Invalid GML: <gml:pos xmlns:gml="http://www.opengis.net/gml/3.2">-758000.00 -1055700.00</gml:pos>
Invalid GML: <gml:pos xmlns:gml="http://www.opengis.net/gml/3.2">-758889.00 -1053755.00</gml:pos>
Invalid GML: <gml:pos xmlns:gml="http://www.opengis.net/gml/3.2">-759963.00 -1055745.00</gml:pos>
Invalid GML: <gml:pointMembers xmlns:gml="http://www.opengis.net/gml/3.2"><gml:Point gml:id="DKU.699306.1"><gml:pos>-759558.65 -1055810.00</gml:pos></gml:Point></gml:pointMembers>
Exception in thread "main" java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2086)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
        at com.fordfrog.ruian2pgsql.gml.GMLUtils.isValidGML(GMLUtils.java:250)
        at com.fordfrog.ruian2pgsql.gml.GMLUtils.createGMLString(GMLUtils.java:132)
        at com.fordfrog.ruian2pgsql.gml.GMLReader.readGMLElement(GMLReader.java:90)
        at com.fordfrog.ruian2pgsql.gml.GMLReader.readGML(GMLReader.java:60)
        at com.fordfrog.ruian2pgsql.utils.Utils.processGML(Utils.java:706)
        at com.fordfrog.ruian2pgsql.utils.Utils.processGeometrieElement(Utils.java:586)
        at com.fordfrog.ruian2pgsql.utils.Utils.processGeometrie(Utils.java:546)
        at com.fordfrog.ruian2pgsql.convertors.KatastralniUzemiConvertor.processElement(KatastralniUzemiConvertor.java:162)
        at com.fordfrog.ruian2pgsql.convertors.KatastralniUzemiConvertor.processElement(KatastralniUzemiConvertor.java:41)
        at com.fordfrog.ruian2pgsql.convertors.AbstractSaveConvertor.convert(AbstractSaveConvertor.java:164)
        at com.fordfrog.ruian2pgsql.convertors.CollectionConvertor.processElement(CollectionConvertor.java:93)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.DataConvertor.processElement(DataConvertor.java:191)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.ExchangeFormatConvertor.processElement(ExchangeFormatConvertor.java:73)
        at com.fordfrog.ruian2pgsql.convertors.AbstractConvertor.convert(AbstractConvertor.java:77)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.processElement(MainConvertor.java:329)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.readInputStream(MainConvertor.java:308)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.processFile(MainConvertor.java:265)
        at com.fordfrog.ruian2pgsql.convertors.MainConvertor.convert(MainConvertor.java:138)
        at com.fordfrog.ruian2pgsql.App.main(App.java:133)

Díky za radu

**Comment by shr3k** [comment]
--convert-to-ewkt --linearize-ewkt nepomůže?
